kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: maksimpesetski/gateway:f83668c
          imagePullPolicy: Always
          ports:
            - name: gateway
              containerPort: 3007
          env:
            - name: APP_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007